### ISSUE TITLE
Date Night main text Changes

### ISSUE THREAD

**Issue by sstephensMCSE** [gehanstedt/date-night#6]
capitalize "n" and change font to white

**Comment by sstephensMCSE** [comment]
completed

**Comment by DexBurns25** [comment]
Completed - 2. Update Date night section to do the following:  
a.	Remove Zipcode option removed zip code function from date night section

**Comment by DexBurns25** [comment]
Completed - b. Make Options font larger – Completed we made Fonts larger and the new color to white
Completed - c. Make City, State font a lighter color (possibly white) – Completed

**Comment by DexBurns25** [comment]
Completed - 
•       Main line: reduce font size and have only as two lines. Padding needed for title line so it all lines up
•	Description: needs tighter line spacing
•	Address needs to have a fixed margin so lines won’t wrap
6.	Remove wording from pictures using as breaks between sections

**Comment by DexBurns25** [comment]
These task has been completed.
